NANOSECONDS = 1
MICROSECOND = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECOND
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {
    'address' : '*--official-mining-reward--*'
}